# Generated by Django 2.1.3 on 2018-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_auto_20181201_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rap', 'Rap'), ('Rock', 'Rock'), ('Classical music', 'Classical music'), ('Electonic music', 'Electonic music')], max_length=25, verbose_name='Жанр'),
        ),
    ]
