# Generated by Django 2.1.3 on 2018-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0003_auto_20181201_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, unique=True),
        ),
    ]
