# Generated by Django 2.1.3 on 2018-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0004_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rap', 'Rap'), ('Classical music', 'Classical music'), ('Electonic music', 'Electonic music'), ('Rock', 'Rock')], max_length=25, verbose_name='Жанр'),
        ),
    ]
