# Generated by Django 2.1.3 on 2018-12-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0007_auto_20181202_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Rap', 'Rap'), ('Classical music', 'Classical music'), ('Electonic music', 'Electonic music')], max_length=25, verbose_name='Жанр'),
        ),
    ]
