# Generated by Django 2.1.3 on 2018-12-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0008_auto_20181202_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rap', 'Rap'), ('Rock', 'Rock'), ('Electonic music', 'Electonic music'), ('Classical music', 'Classical music')], max_length=25, verbose_name='Жанр'),
        ),
    ]
