# Generated by Django 2.1.3 on 2018-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0011_auto_20181203_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rap', 'Rap'), ('Electonic music', 'Electonic music'), ('Rock', 'Rock'), ('Classical music', 'Classical music')], max_length=25, verbose_name='Жанр'),
        ),
    ]
