# Generated by Django 2.1.3 on 2018-11-12 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('password', models.CharField(max_length=10, verbose_name='ФИО')),
                ('disk', models.CharField(max_length=3, verbose_name='Диск')),
                ('course', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, verbose_name='Курсы'), size=None), size=None)),
                ('delivery', models.CharField(choices=[('Бесплатная', 'Бесплатная'), ('Быстрая', 'Быстрая')], max_length=20, verbose_name='Способ доставки')),
                ('address', models.TextField(verbose_name='Введите адрес доставки')),
            ],
        ),
    ]
