# Generated by Django 2.1.3 on 2018-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('password', models.CharField(max_length=10, verbose_name='Пароль')),
                ('disk', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD')], max_length=3, verbose_name='Диск')),
                ('course', models.CharField(choices=[('Курсу по Фотошопу', 'Курсу по Фотошопу'), ('Курсы по PHP', 'Курсы по PHP'), ('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer')], max_length=30, verbose_name='Курсы')),
                ('delivery', models.CharField(choices=[('Быстрая', 'Быстрая'), ('Бесплатная', 'Бесплатная')], max_length=20, verbose_name='Способ доставки')),
                ('address', models.TextField(verbose_name='Введите адрес доставки')),
            ],
        ),
    ]
