# Generated by Django 2.1.3 on 2018-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Быстрая', 'Быстрая'), ('Бесплатная', 'Бесплатная')], max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Пароль'),
        ),
    ]
