# Generated by Django 2.1.3 on 2018-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20181202_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсы по PHP', 'Курсы по PHP'), ('Курсу по Фотошопу', 'Курсу по Фотошопу'), ('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer')], max_length=30, verbose_name='Курсы'),
        ),
    ]
