# Generated by Django 2.1.3 on 2018-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20181202_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Бесплатная', 'Бесплатная'), ('Быстрая', 'Быстрая')], max_length=20, verbose_name='Способ доставки'),
        ),
    ]
