# Generated by Django 2.1.3 on 2018-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_auto_20181202_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='order',
            name='disk',
            field=models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD')], max_length=3, verbose_name='Диск'),
        ),
    ]
