# Generated by Django 2.1.3 on 2018-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_auto_20181202_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='ФИО')),
                ('message', models.CharField(max_length=30, verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer'), ('Курсу по Фотошопу', 'Курсу по Фотошопу'), ('Курсы по PHP', 'Курсы по PHP')], max_length=30, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('CD', 'CD')], max_length=3, verbose_name='Диск'),
        ),
    ]
