# Generated by Django 2.1.3 on 2018-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_auto_20181202_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer'), ('Курсы по PHP', 'Курсы по PHP'), ('Курсу по Фотошопу', 'Курсу по Фотошопу')], max_length=30, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Быстрая', 'Быстрая'), ('Бесплатная', 'Бесплатная')], max_length=20, verbose_name='Способ доставки'),
        ),
    ]
