# Generated by Django 2.1.3 on 2018-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0015_auto_20181203_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegExpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_1', models.CharField(max_length=30, verbose_name='Форма 1')),
                ('form_2', models.CharField(max_length=30, verbose_name='Форма 2')),
                ('form_3', models.CharField(max_length=30, verbose_name='Форма 3')),
                ('form_4', models.CharField(max_length=30, verbose_name='Форма 4')),
                ('form_5', models.CharField(max_length=30, verbose_name='Форма 5')),
                ('form_6', models.CharField(max_length=30, verbose_name='Форма 6')),
                ('form_7', models.CharField(max_length=30, verbose_name='Форма 7')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer'), ('Курсы по PHP', 'Курсы по PHP'), ('Курсу по Фотошопу', 'Курсу по Фотошопу')], max_length=30, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disk',
            field=models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD')], max_length=3, verbose_name='Диск'),
        ),
    ]
