# Generated by Django 2.1.3 on 2018-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0019_auto_20181203_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='regexpmodel',
            name='form_10',
            field=models.CharField(default='', max_length=30, verbose_name='Форма 10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regexpmodel',
            name='form_7',
            field=models.CharField(default='', max_length=30, verbose_name='Форма 7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regexpmodel',
            name='form_8',
            field=models.CharField(default='', max_length=30, verbose_name='Форма 8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regexpmodel',
            name='form_9',
            field=models.CharField(default='', max_length=30, verbose_name='Форма 9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсу по Фотошопу', 'Курсу по Фотошопу'), ('Курсы по PHP', 'Курсы по PHP'), ('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer')], max_length=30, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Быстрая', 'Быстрая'), ('Бесплатная', 'Бесплатная')], max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disk',
            field=models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD')], max_length=3, verbose_name='Диск'),
        ),
    ]
