# Generated by Django 2.1.3 on 2018-12-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0023_auto_20181210_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
        migrations.AlterField(
            model_name='order',
            name='course',
            field=models.CharField(choices=[('Курсы по Adobe Dreamweawer', 'Курсы по Adobe Dreamweawer'), ('Курсу по Фотошопу', 'Курсу по Фотошопу'), ('Курсы по PHP', 'Курсы по PHP')], max_length=30, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Быстрая', 'Быстрая'), ('Бесплатная', 'Бесплатная')], max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('CD', 'CD')], max_length=3, verbose_name='Диск'),
        ),
    ]
